### ISSUE TITLE
dpath only searches the last YAML document

### ISSUE THREAD

**Issue by mjcarman** [renormalist/app-dpath#6]
YAML files/streams can contain multiple documents. When dpath reads a YAML stream via

```
$data = YAML::Any::Load($filecontent);
```

Only the contents of the last document are captured. (i.e., it's equivalent to `$x = (1, 2, 3)`, which discards 1 & 2 and sets `$x` to 3).

dpath should search in all YAML documents.

This can be fixed by changing `_read_in` to do

```
$data = [YAML::Any::Load($filecontent)];
```

and updating `search` to check for an ARRAY reference and loop over the contents. (Pull request to come.)

**Comment by renormalist** [comment]
Released with app-dpath 0.07. Thanks.
